name: ndialog
description: Customize your dialog's style much easier with NDialog, animate the show transition, or show the progress dialog most simply.
version: 4.5.0+1
homepage: https://nizwar.github.io/ndialog/
repository: https://github.com/nizwar/ndialog

environment:
  sdk: ">=2.12.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter  

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: "NDialog logo image"
    path: images/logo.png